DROP TABLE IF EXISTS GENERALJOURNALHEADER CASCADE;

CREATE TABLE GENERALJOURNALHEADER (
    journal_id     TEXT   NOT NULL UNIQUE,          -- business id (GJ-000123)
    document_date  DATE   NOT NULL,
    type           TEXT   NOT NULL,                 -- journal type
    description    TEXT,
    status         TEXT   NOT NULL,                 -- 'draft' | 'posted'
    posted         TIMESTAMPTZ,                     -- NULL until posted
    company_id     INT   NOT NULL,                  -- owning company
    record_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
