-- psql -d myerp -c "\i schema.sql"         -- run the schema script
-- psql -d myerp -c "\i dummyData.sql"      -- run the dummyData script

DROP TABLE IF EXISTS GENERALJOURNALTABLE;
DROP TABLE IF EXISTS GENERALJOURNALTRANS;
DROP TABLE IF EXISTS FINANCIALDIMENSIONS;
DROP TABLE IF EXISTS FINANCIALDIMENSIONVALUES;
DROP TABLE IF EXISTS FINANCIALDIMENSIONCOMBOS;

CREATE TABLE GENERALJOURNALTABLE (

    journal_id     TEXT   NOT NULL UNIQUE,          
    document_date  DATE   NOT NULL,
    type           TEXT   NOT NULL,                 
    description    TEXT,
    status         TEXT   NOT NULL,                 
    posted         TIMESTAMPTZ,                     
    version_id     INT NOT NULL,
    company_id     INT   NOT NULL,                  
    record_id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY

);

CREATE TABLE GENERALJOURNALTRANS (

    journal_id      VARCHAR(36) NOT NULL,            -- FK to general_journal_header
    line_id         INT NOT NULL,                    -- line number inside journal
    account         VARCHAR(50) NOT NULL,            -- GL account number
    dimension       INT,
    description     TEXT,                            -- optional description
    debit           NUMERIC(18, 2) DEFAULT 0 NOT NULL,
    credit          NUMERIC(18, 2) DEFAULT 0 NOT NULL,
    offsetAccount   VARCHAR(50),            -- GL account number
    offsetDimension INT,
    company_id      INT NOT NULL,                    -- FK to companies table
    version_id      INT NOT NULL,
    record_id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY

);

CREATE TABLE FINANCIALDIMENSIONS (

    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100),                         -- allow NULL for "unused"
    in_use      BOOLEAN NOT NULL DEFAULT TRUE,
    company_id  INT NOT NULL

);

CREATE TABLE FINANCIALDIMENSIONVALUES (
    
    code        VARCHAR(50) NOT NULL,
    description TEXT,
    dimension   INT NOT NULL ,
    company_id  INT NOT NULL,
    record_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY

);

CREATE TABLE FINANCIALDIMENSIONCOMBOS (

    -- The 8 dimension value references (nullable if not used)
    fd1         VARCHAR(50),
    fd2         VARCHAR(50),
    fd3         VARCHAR(50),
    fd4         VARCHAR(50),
    fd5         VARCHAR(50),
    fd6         VARCHAR(50),
    fd7         VARCHAR(50),
    fd8         VARCHAR(50),
    version_id  INT NOT NULL,
    company_id  INT NOT NULL,
    record_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    
);

CREATE UNIQUE INDEX uq_fd_combo_expr ON FINANCIALDIMENSIONCOMBOS (
  company_id,
  (coalesce(fd1,'')), (coalesce(fd2,'')), (coalesce(fd3,'')), (coalesce(fd4,'')),
  (coalesce(fd5,'')), (coalesce(fd6,'')), (coalesce(fd7,'')), (coalesce(fd8,''))
);

-- server side session data
CREATE TABLE IF NOT EXISTS SESSIONS (
  sid           TEXT PRIMARY KEY,                 
  user_id       VARCHAR(50) NOT NULL,
  company_id    INTEGER,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen     TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at    TIMESTAMPTZ NOT NULL              
);

-- Checking for Expiration
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON SESSIONS (expires_at);

-- Query by User
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON SESSIONS (user_id);
