DROP TABLE IF EXISTS GENERALJOURNALTABLE;
DROP TABLE IF EXISTS GENERALJOURNALTRANS;
DROP TABLE IF EXISTS FINANCIALDIMENSIONS;
DROP TABLE IF EXISTS FINANCIALDIMENSIONVALUES;
DROP TABLE IF EXISTS FINANCIALDIMENSIONCOMBOS;

CREATE TABLE GENERALJOURNALTABLE (

    journal_id     TEXT   NOT NULL UNIQUE,          -- business id (GJ-000123)
    document_date  DATE   NOT NULL,
    type           TEXT   NOT NULL,                 -- journal type
    description    TEXT,
    status         TEXT   NOT NULL,                 -- 'draft' | 'posted'
    posted         TIMESTAMPTZ,                     -- NULL until posted
    company_id     INT   NOT NULL,                  -- owning company
    record_id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

CREATE TABLE GENERALJOURNALTRANS (

    journal_id    VARCHAR(36) NOT NULL,            -- FK to general_journal_header
    line_id       INT NOT NULL,                    -- line number inside journal
    account       VARCHAR(50) NOT NULL,            -- GL account number
    description   TEXT,                            -- optional description
    debit         NUMERIC(18, 2) DEFAULT 0 NOT NULL,
    credit        NUMERIC(18, 2) DEFAULT 0 NOT NULL,
    dimension     INT,
    company_id    INT NOT NULL,                    -- FK to companies table
    version_id    INT NOT NULL,
    record_id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY

);

CREATE TABLE FINANCIALDIMENSIONS (

    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100),                         -- allow NULL for "unused"
    in_use      BOOLEAN NOT NULL DEFAULT TRUE,
    company_id  INT NOT NULL

);

CREATE TABLE FINANCIALDIMENSIONVALUES (
    
    code        VARCHAR(50) NOT NULL,
    description TEXT,
    dimension   INT NOT NULL ,
    company_id  INT NOT NULL,
    record_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY

);

CREATE TABLE FINANCIALDIMENSIONCOMBOS (

    -- The 8 dimension value references (nullable if not used)
    fd1         VARCHAR(50),
    fd2         VARCHAR(50),
    fd3         VARCHAR(50),
    fd4         VARCHAR(50),
    fd5         VARCHAR(50),
    fd6         VARCHAR(50),
    fd7         VARCHAR(50),
    fd8         VARCHAR(50),
    company_id  INT NOT NULL,
    record_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    
);
